### ISSUE TITLE
Identifier starting with ∫ incorrectly parsed (?)

### ISSUE THREAD

**Issue by jagot** [tree-sitter/tree-sitter-julia#101]
I hope this is the right place to report this.

I noticed Emacs incorrectly highlighted a code snippet of mine, where some identifiers start with `∫`:

<img width="419" alt="image" src="https://user-images.githubusercontent.com/117947/231681777-2a391ba0-97aa-48fe-914b-cc867e267738.png">

I can reduce this to
```julia
∫A
∑a
```
which `treesit-explore-mode` report as
```lisp
(source_file
 (ERROR (ERROR))
 (identifier) \n (identifier) \n)
```
so identifiers starting with `∑` are correctly identified, but not those starting with `∫`.

Thank you for a very nice parser otherwise!

**Comment by savq** [comment]
Both `∑` and `∫` are in the unicode character category [Sm](https://www.fileformat.info/info/unicode/category/Sm/list.htm) (math symbols). Most of the characters in this category are operators, so the ones that work as identifiers are "hand-picked". The valid characters are listed in [`julia/src/flisp/julia_extensions.c`](https://github.com/JuliaLang/julia/blob/master/src/flisp/julia_extensions.c#L79).

I never added the whole list to the tree-sitter parser because 1. some are very confusing (like the 7 versions of nabla), and 2. very few of these characters are actually used in the wild.

**Comment by jagot** [comment]
I see your point, but since I'm a sucker for mathematical notation in my code, I would not mind seeing the whole list included :)

**Comment by clason** [comment]
Yes, but there's a definite cost associated to this, since adding symbols increases the state size of the parser -- and this parser is already on the very top end of the largest (and slowest) parsers nvim-treesitter supports.

**Comment by savq** [comment]
The current `julia_extensions.c` doesn't make it very obvious, but the characters we already allow are all in two character ranges `∀-∇, ∎-∑`, which is good because it means we can stuff more characters without computing more comparisons. If we add a third range for integrals `∫-∳` I think we're all good.
