### ISSUE TITLE
Readme should state on how to install the grammar

### ISSUE THREAD

**Issue by mauro3** [tree-sitter/tree-sitter-julia#115]
That would be helpful to get started.  As the entry-point for this, https://github.com/ronisbr/julia-ts-mode, is not more specific either.

**Comment by savq** [comment]
Unfortunately different editors and tools use different conventions for compilation and paths, so we cannot add installation instructions that work for everyone.

I'd suggest you open and issue in julia-ts-mode to clarify how this is done in Emacs.

For development of the grammar itself, we could add some emacs specific notes to our CONTRIBUTING file, like the section explaining how to use a local grammar in neovim. I didn't write about emacs because I don't know emacs 😅

**Comment by mauro3** [comment]
Thanks for the clarification, makes sense.  I'll open the issue with julia-ts-mode
